language: go

go:
  - 1.7.1

env:
  global:
    - SSH_KEY="darkowlzz.github.io"
    - GIT_NAME="darkowlzz"
    - GIT_EMAIL="me@darkowlzz.space"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="source"

before_install:
  - openssl aes-256-cbc -K $encrypted_358bf1b07723_key -iv $encrypted_358bf1b07723_iv -in darkowlzz.github.io.enc -out darkowlzz.github.io -d

install: true

before_script:
  - go get github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo

script:
  - hugo --theme=after-dark

after_success:
  - ./scripts/deploy.sh
