language: go

go:
  - 1.8.3

env:
  global:
    - SSH_KEY="darkowlzz.github.io"
    - GIT_NAME="darkowlzz"
    - GIT_EMAIL="me@darkowlzz.space"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="source"

before_install:
  - openssl aes-256-cbc -K $encrypted_358bf1b07723_key -iv $encrypted_358bf1b07723_iv -in darkowlzz.github.io.enc -out darkowlzz.github.io -d

install: true

before_script:
  - wget -O ~/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.24.1/hugo_0.24.1_Linux-64bit.tar.gz
  - tar -zxvf ~/hugo.tar.gz -C ~/

script:
  - ~/hugo --theme=after-dark

after_success:
  - ./scripts/deploy.sh
