baseURL = "https://darkowlzz.github.io/"
languageCode = "en-us"
title = "darkowlzz"
theme = "after-dark"
googleAnalytics = "UA-63771901-5"
disqusShortname = "darkowlzz-space"

[params]
    site_title = "darkowlzz"

[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = -110
    url = "/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = -100
    url = "/about/me"
