baseURL = "https://darkowlzz.github.io/"
languageCode = "en-us"
title = "darkowlzz"
googleAnalytics = "UA-63771901-5"
disqusShortname = "darkowlzz-space"

[params]
    site_title = "darkowlzz"

[[menu.main]]
    name = "github"
    identifier = "github"
    weight = -110
    url = "https://github.com/darkowlzz"

[[menu.main]]
    name = "twitter"
    identifier = "twitter"
    weight = -100
    url = "https://twitter.com/darkowlzz"

[[menu.main]]
    name = "old logs"
    identifier = "oldlogs"
    weight = -90
    url = "https://codingowl.tumblr.com"

[[menu.main]]
    name = "open hub"
    identifier = "openhub"
    url = "https://www.openhub.net/accounts/darkowlzz"
